#!/bin/bash
set -euo pipefail

# init-project.sh — scaffold a per-project WordPress workspace
# Usage: ./init-project.sh [--name <name>] [--theme <slug>] [--yes] [<target-dir>]

# Defaults
TARGET_DIR="${1:-.}"
PROJECT_NAME=""
THEME_SLUG=""
SKIP_CONFIRM=0

# Parse flags
while [[ $# -gt 0 ]]; do
  case "$1" in
    --name)
      PROJECT_NAME="$2"
      shift 2
      ;;
    --theme)
      THEME_SLUG="$2"
      shift 2
      ;;
    --yes)
      SKIP_CONFIRM=1
      shift
      ;;
    *)
      TARGET_DIR="$1"
      shift
      ;;
  esac
done

# Resolve target directory to absolute path
TARGET_DIR="$(cd "$TARGET_DIR" && pwd)"

# Idempotency: refuse if docs/ exists
if [[ -d "$TARGET_DIR/docs" ]]; then
  echo "Error: $TARGET_DIR/docs/ already exists. This directory is already a project." >&2
  exit 1
fi

# Set PROJECT_NAME from target dir basename if not provided
if [[ -z "$PROJECT_NAME" ]]; then
  PROJECT_NAME="$(basename "$TARGET_DIR")"
fi

# Sanitize theme slug (lowercase, hyphens, alphanumeric)
if [[ -z "$THEME_SLUG" ]]; then
  THEME_SLUG="$(echo "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | tr -cs '[:alnum:]' '-' | sed 's/^-//;s/-$//')"
fi

# Confirmation
if [[ $SKIP_CONFIRM -eq 0 ]]; then
  echo "Project Name: $PROJECT_NAME"
  echo "Theme Slug: $THEME_SLUG"
  echo "Target Dir: $TARGET_DIR"
  read -p "Continue? (y/n) " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Cancelled."
    exit 1
  fi
fi

# Create directory structure
mkdir -p "$TARGET_DIR/docs/02-wireframes"
mkdir -p "$TARGET_DIR/docs/03-content"
mkdir -p "$TARGET_DIR/docs/06-images"
mkdir -p "$TARGET_DIR/docs/checkpoints"
mkdir -p "$TARGET_DIR/src/wp-content/themes/$THEME_SLUG"
mkdir -p "$TARGET_DIR/.claude"

# Copy templates
TEMPLATE_DIR="$HOME/mvp-builder/templates/wordpress"

cp "$TEMPLATE_DIR/requirements.template.md" "$TARGET_DIR/docs/00-requirements.md"
cp "$TEMPLATE_DIR/sitemap.template.md" "$TARGET_DIR/docs/01-sitemap.md"
cp "$TEMPLATE_DIR/brand-voice.template.md" "$TARGET_DIR/docs/brand-voice.md"
cp "$TEMPLATE_DIR/design.template.md" "$TARGET_DIR/docs/04-design.md"
cp "$TEMPLATE_DIR/image-guidelines.template.md" "$TARGET_DIR/docs/image-guidelines.md"
cp "$TEMPLATE_DIR/coding-standards.md" "$TARGET_DIR/docs/coding-standards.md"
cp "$TEMPLATE_DIR/known-issues.md" "$TARGET_DIR/docs/99-known-issues.md"

# Stub image-prompts.md
cat > "$TARGET_DIR/docs/05-image-prompts.md" << 'EOF'
# Image Prompts

*Generated by stage 5. Empty until then.*
EOF

# Stub CHANGELOG.md
cat > "$TARGET_DIR/docs/CHANGELOG.md" << 'EOF'
# CHANGELOG

## Unreleased

- chore: project initialized via mvp-builder-wordpress-init.
EOF

# Stub theme files
cat > "$TARGET_DIR/src/wp-content/themes/$THEME_SLUG/style.css" << EOF
/*
Theme Name: $PROJECT_NAME
Author: mvp-builder
Version: 0.1.0
Text Domain: $THEME_SLUG
Domain Path: /languages
Requires at least: 6.0
Requires PHP: 8.0
*/
EOF

cat > "$TARGET_DIR/src/wp-content/themes/$THEME_SLUG/functions.php" << EOF
<?php
// $THEME_SLUG functions — populated by stage 4.
EOF

cat > "$TARGET_DIR/src/wp-content/themes/$THEME_SLUG/index.php" << EOF
<?php
// Block theme — main template lives at templates/index.html or template-parts/. Populated by stage 4.
EOF

# Initialize git if needed
if [[ ! -d "$TARGET_DIR/.git" ]]; then
  git -C "$TARGET_DIR" init -q
fi

# Summary
echo ""
echo "✓ Project initialized: $PROJECT_NAME"
echo "  Location: $TARGET_DIR"
echo "  Theme: $THEME_SLUG"
echo ""
echo "Created:"
echo "  - docs/ with 00-requirements, 01-sitemap, 04-design, brand-voice, coding-standards, image-guidelines, 99-known-issues"
echo "  - docs/02-wireframes/, 03-content/, 06-images/, checkpoints/"
echo "  - src/wp-content/themes/$THEME_SLUG/ with style.css, functions.php, index.php"
echo "  - .git/ (git repository)"
echo ""
echo "Next: /mvp-builder-wordpress-plan"
